### ISSUE TITLE
Open to collaboration?

### ISSUE THREAD

**Issue by progfolio** [fbrosda/pacdiff.el#2]
I like the idea of this mode.
I set out to do some light refactoring this morning, but ended up touching most of the code base.
The functionality is the same, but I simplified the implementation and (IMO) cleaned up the interface a bit.
Take a look at the rewrite I did here:

https://github.com/progfolio/pacdiff.el/blob/rewrite/pacdiff.el

Would  you be interested in merging this?

**Comment by fbrosda** [comment]
Great you like the idea and as I don't have much experience with emacs lisp it's nice to see how this is properly done^^ So yes I would definitely merge this. 

There is one thing, which bothers me a bit though. Redrawing the contents of the buffer, after overwriting/deleting a file causes the cursor to jump to the beginning of the buffer.  If I deliberately skipped a few files in the beginning, then I have to skip over these files again.

I think, it should be enough, to keep the cursor on the same line as this will automatically be the next entry, after the current one got deleted. 

Do you want to adjust the code, or should I take a look, after merging your changes?

**Comment by progfolio** [comment]
Fabian Brosda ***@***.***> writes:

> Great you like the idea and as I don't have much experience with 
> emacs lisp it's nice to see
> how this is properly done^^ So yes I would definitely merge 
> this.

Cool!
 
> There is one thing, which bothers me a bit though. Redrawing the 
> contents of the buffer,
> after overwriting/deleting a file causes the cursor to jump to 
> the beginning of the buffer. If
> I deliberately skipped a few files in the beginning, then I have 
> to skip over these files
> again.
>
> I think, it should be enough, to keep the cursor on the same 
> line as this will automatically
> be the next entry, after the current one got deleted.
>
> Do you want to adjust the code, or should I take a look, after 
> merging your changes?

I made an adjustment which does its best to preserve the current 
column and line.
Normally we wrap any movement in `save-excursion`, but that won't 
work here because the buffer text is altered.
